apiVersion: 1

datasources:
  - name: Chicken TimescaleDB
    uid: chicken_timescaledb
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: hara

    # Keep this too; it does not hurt.
    database: chicken_tracking

    secureJsonData:
      password: "123456"

    jsonData:
      database: chicken_tracking
      sslmode: disable
      timescaledb: true

    isDefault: true
    editable: true