DEEPSORT:
#  DETECTION_MODEL_PATH: "C:/Users/tliu25/workspace/ultralytics/ultralytics/hara/weights/yolo11l-obb-chicken-0607.pt"
  DETECTION_MODEL_PATH: "D:/chicken_project/experiment6report/running/obb_hold4_10min/weights/last.pt"
#  REID_CKPT: ""
#  REID_CKPT: "deep_sort/deep_sort/deep/checkpoint/ckpt_person.t7"
  REID_CKPT: "C:/Users/tliu25/workspace/ultralytics/ultralytics/hara/hara_reid/outputs/best_osnet.pth"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.7
  N_INIT: 3
  NN_BUDGET: 100
  MAX_ID_POOL: 15
  RECONNECTION_DISTANCE_THRESHOLD: 200
  REUSE_ID_ASSIGNMENT_DISTANCE_THRESHOLD: 200
  USE_REID: False
  USE_ROTATED_FEATURES: True
  USE_OPTIMIZATION: True
  REUSE_ID: True # use_optimization & reuse_id to turn on it.
  DETECTION_OPTIMIZATION_ON: False
  TRACK_RECONNECTION_ON: False
  MAX_AGE: 30
#  USE_OPTIMIZATION: False
#  MAX_AGE: 30
  TRACKING_CSV_PATH: tracking_output1.csv
#  VIDEO_PATH: F:/20251002/RGB_mock/seg1.mp4
#  VIDEO_PATH: E:/temp/20250827T122000Z_20250827T124000Z.mkv
  VIDEO_PATH: D:/chicken_project/experiment5reid/special case videos/fold4 chicken fighting.mp4
  RESULT_PATH: interaction_opt_150.mp4
  MAX_FRAME: 20000